---
title: "Project tips + resources"
---

## Data sources

Some resources that may be helpful as you find data:

-   [Collection of Open Datasets](https://github.com/awesomedata/awesome-public-datasets)
-   [Open Government Data (D-A-CH-LI)](https://www.govdata.de)
-   [EU Open Data](https://data.europa.eu/euodp/en/home)
-   [Statistisches Bundesamt](https://www-genesis.destatis.de/genesis/online/data)
-   [Regionalstatistik](https://www.regionalstatistik.de/genesis/online/)
-   [Germany Zensus2011](https://www.zensus2011.de/DE/Home/Aktuelles/DemografischeGrunddaten.html?nn=559100)
-   [OECD](https://data.oecd.org)
-   [World Health Organization](https://www.who.int/gho/database/en/)
-   [The National Bureau of Economic Research](https://data.nber.org/data/)
-   [International Monetary Fund](https://data.imf.org/?sk=388DFA60-1D26-4ADE-B505-A05A558D9A42&sId=1479329328660)
-   [General Social Survey](http://gss.norc.org/)
-   [United Nations Data](http://data.un.org/)
-   [United Nations Statistics Division](https://unstats.un.org/home/)
-   [U.K. Data](https://data.gov.uk/)
-   [U.S. Data](https://www.data.gov/)
-   [U.S. Census Data](https://www.census.gov/data.html)
-   [European Statistics](https://ec.europa.eu/eurostat/)
-   [Statistics Canada](https://www.statcan.gc.ca/eng/start)
-   [Pew Research](https://www.pewresearch.org/download-datasets/)
-   [UNICEF](https://data.unicef.org/)
-   [CDC](https://www.cdc.gov/datastatistics/index.html)
-   [World Bank](https://datacatalog.worldbank.org/)
-   [Election Studies](https://electionstudies.org//)

## Tips

-   Ask questions if any of the expectations are unclear.

-   GitHub merge conflicts will happen, issues will arise, and that's fine! Commit and push often, and ask questions when stuck.

-   Make sure each team member is contributing, both in terms of quality and quantity of contribution (I will be reviewing commits from different team members).

-   All team members are expected to contribute equally to the completion of this assignment and group assessments will be given at its completion - anyone judged to not have sufficient contributed to the final product will have their grade penalized. While different teams members may have different backgrounds and abilities, it is the responsibility of every team member to understand how and why all code and approaches in the assignment works.
