---
title: "Project description"
number-sections: true
---


## Introduction

By the end of the course, students should be able to 

1. create a **presentation** and **report** using Altair and Quarto 
2. create an interactive **dashboard** with Streamlit and Altair 
3. **document** the creation process in an online Quarto book, utilizing GitHub and GitHub Projects.

All analyses must be done in Python, and all components of the project *must be reproducible* placed inside the repos of your GitHub Organization (organizations are shared accounts where you can collaborate).


## Topic ideas {#sec-topic-ideas}

Identify at least 2 data sets for the topic you're interested in using for the project. The data sets should be suitable to be used alongside the points described in the ["Big Idea Worksheet"](https://docs.google.com/document/d/1-GZvhdbhLYLB_Bo1arj1rgTqbJ5SUoU21vtgbYEhVqk/edit?usp=sharing). Furthermore, it should be possible to create the following chart types: bar chart, scatterplot, line chart, distribution chart and a map. You need to create at least 5 different chart types in the report and dashboard.

If you're unsure where to find data, you can use the list of potential data sources in the [Tips + Resources](project-tips-resources.qmd) section as a starting point. It may also help to think of topics you're interested in investigating and find data sets on those topics.

The purpose of submitting project ideas is to give you time to find data for the project and to make sure you have a data set that can help you be successful in the project.


## Project Components:

1. **Data Story as Presentation and Report (using Altair and Quarto; you can use Quarto or Streamlit to create the report)**
2. **Interactive Dashboard (using Streamlit and Altair)**
3. **Documentation of Creation Process (in a Quarto online book with GitHub and GitHub Projects)**

## Assessment Criteria:

1. Data Story as Presentation and Report (35 points)
- **Relevance (5 points)**: The datasets chosen are relevant and meaningful for the storytelling objective.
- **Visualization & Design (10 points)**: Effective use of color, size, layout, and appropriate visualization types. Avoidance of chart junk.
- **Storytelling & Narrative (10 points)**: The story is clear, concise, insightful, and provides new perspectives on the data.
- **Alignment with Knaflic's Principles (10 points)**: Demonstrated understanding and application of principles from "Storytelling with Data".

Note on the report: You can create the report using a few selected plots. This is possible in Streamlit or Quarto. The aim is to explain the content of the charts in a visually appealing and easy-to-understand way with text.

2. Interactive Dashboard with Streamlit and Altair (35 points)
- **User Experience (10 points)**: Intuitive navigation, clear instructions, and responsive design in Streamlit.
- **Interactivity (10 points)**: Effective use of Altair's and Streamlit's interactivity features to enhance user engagement.
- **Visualization & Design (10 points)**: Effective use of color, size, layout, and appropriate visualization types.
- **Data Relevance & Insightfulness (5 points)**: The dashboard provides meaningful insights and is based on relevant data.

3. Documentation of Creation Process (30 points)
- **Clarity & Structure (8 points)**: Clear table of contents, chapters, sections, and overall flow in the Quarto online book.
- **Technical Proficiency (8 points)**: Demonstrated proficiency in Python programming, integration of Altair visualizations, and use of GitHub and GitHub Projects.
- **Process Explanation (8 points)**: Detailed explanation of the steps taken, challenges faced, and solutions implemented during the creation of the report and dashboard.
- **Accessibility & Design (3 points)**: The online book has a user-friendly interface and provides meaningful text and visualizations.
- **Alignment with Course Literature (3 points)**: Demonstrated understanding and application of principles and techniques from the course literature.

Total Points: 100


## GitHub Organization

You will work on the project with your team. 

1. One team member should create a new **GitHub organization** and invite all other team members and me (my GitHub name is `kirenz`) to the organization.  
2. Create a [GitHub Project](https://kirenz.github.io/lab-toolkit/github.html#github-projects) in your organization and use it to organize your work.
3. Import this [Documentation template](https://github.com/kirenz/documentation-template) to your organization (click on `use this template`)

